### ISSUE TITLE
the tool script should copy the comment from the original ignored alerts list

### ISSUE THREAD

**Issue by ioana-github-enterprise** [whitesource-ps/ws-ignore-future-alerts#19]
Feature Request opened on behalf of Marco Fernandes da Silva from ICW. DE 

"Hello,

I am using the latest version of ws-ignore-future-alerts script provided on https://github.com/whitesource-ps/ws-ignore-future-alerts and I noticed that all the comment field from the original ignored alerts list is no present at the destination.
The comment field usually explains the reason why the alerts were ignored, so I think this information is vital and should be copied as well.
I checked the python script and it confirmed that instead of the original content, the comment is replaced by "automatically ignored by WS utility".

It should be an easy fix, but also pretty helpful.

Thanks for your time and have a nice day,

Marco"

**Comment by NatalyaDalid** [comment]
Hello Marco,

Thank you for raising this enhancement.
The fix has been provided and released. Please download the recent version.

Please let us know if there is anything else we can help with.

Best regards,
PS team
