### ISSUE TITLE
[BUG] [ws-ignore-future-alerts] Documentation is refering to 'projectName' instead of 'destProjectName'

### ISSUE THREAD

**Issue by guillaumelamirand** [whitesource-ps/ws-ignore-future-alerts#8]
**Bug Description**  
The documentation is describing how to define the target project using 'projectName' and 'projectVersion', except that the code is waiting for 'destProjectName' and 'destProjectVersion'.

**Steps to Reproduce**  
1. Go to 'https://github.com/whitesource-ps/ws-ignore-future-alerts#configuration-parameters'
2. Check the parameter are wrong for the target project 

**Expected Behavior**  
Documentation is up to date according what the python script is waiting.

**Screenshots**  
Here the documentation extract: 
![image](https://user-images.githubusercontent.com/4324887/124740648-46363200-df1b-11eb-82c2-fa768be57958.png)

Here the code:
![image](https://user-images.githubusercontent.com/4324887/124740700-5221f400-df1b-11eb-91ba-4c3824b98a82.png)

**Comment by NatalyaDalid** [comment]
Hi @guillaumelamirand . 

Thank you for your collaboration and contrubution.

The fix has been released and the new version is now available.

Regards,
WhiteSource PS team

**Comment by guillaumelamirand** [comment]
HI @NatalyaDalid 

Everything looks fine, thank you.
